//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public decimal Amount { get; set; }
        public int Status { get; set; }
        public int CarParkId { get; set; }
        public int ParkingLotId { get; set; }
        public string AspNetUserId { get; set; }
        public string TransactionCode { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CarPark CarPark { get; set; }
        public virtual ParkingLot ParkingLot { get; set; }
    }
}
