//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Sdk
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaApi : Capstone.Sdk.BaseSdkApi<Capstone.Models.Entities.Area, Capstone.ViewModels.AreaViewModel, Capstone.Models.Entities.Services.IAreaService>
    {
    	
    }
}
