//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IBookingHistoryRepository : SkyWeb.DatVM.Data.IBaseRepository<BookingHistory>
    {
    }
    
    public partial class BookingHistoryRepository : SkyWeb.DatVM.Data.BaseRepository<BookingHistory>, IBookingHistoryRepository
    {
    	public BookingHistoryRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    	{
    	}
    }
}
