//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICarParkRepository : SkyWeb.DatVM.Data.IBaseRepository<CarPark>
    {
    }
    
    public partial class CarParkRepository : SkyWeb.DatVM.Data.BaseRepository<CarPark>, ICarParkRepository
    {
    	public CarParkRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    	{
    	}
    }
}
