//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IItemRepository : SkyWeb.DatVM.Data.IBaseRepository<Item>
    {
    }
    
    public partial class ItemRepository : SkyWeb.DatVM.Data.BaseRepository<Item>, IItemRepository
    {
    	public ItemRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    	{
    	}
    }
}
