//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IBookingHistoryService : SkyWeb.DatVM.Data.IBaseService<BookingHistory>
    {
    }
    
    public partial class BookingHistoryService : SkyWeb.DatVM.Data.BaseService<BookingHistory>, IBookingHistoryService
    {
        public BookingHistoryService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IBookingHistoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
