//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICarParkService : SkyWeb.DatVM.Data.IBaseService<CarPark>
    {
    }
    
    public partial class CarParkService : SkyWeb.DatVM.Data.BaseService<CarPark>, ICarParkService
    {
        public CarParkService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICarParkRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
