//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IItemService : SkyWeb.DatVM.Data.IBaseService<Item>
    {
    }
    
    public partial class ItemService : SkyWeb.DatVM.Data.BaseService<Item>, IItemService
    {
        public ItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
