//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IParkingLotService : SkyWeb.DatVM.Data.IBaseService<ParkingLot>
    {
    }
    
    public partial class ParkingLotService : SkyWeb.DatVM.Data.BaseService<ParkingLot>, IParkingLotService
    {
        public ParkingLotService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IParkingLotRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
