//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistoryViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Capstone.Models.Entities.BookingHistory>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int CarParkId { get; set; }
    			public virtual string AspNetUserId { get; set; }
    			public virtual System.DateTime BookingTime { get; set; }
    			public virtual Nullable<int> ParkingLotId { get; set; }
    	
    	public BookingHistoryViewModel() : base() { }
    	public BookingHistoryViewModel(Capstone.Models.Entities.BookingHistory entity) : base(entity) { }
    
    }
}
