//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Capstone.Models.Entities.Item>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Name { get; set; }
    			public virtual byte[] Address { get; set; }
    			public virtual int Type { get; set; }
    			public virtual int Status { get; set; }
    			public virtual int ParkingLotId { get; set; }
    			public virtual int CarParkId { get; set; }
    	
    	public ItemViewModel() : base() { }
    	public ItemViewModel(Capstone.Models.Entities.Item entity) : base(entity) { }
    
    }
}
