//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Capstone.Models.Entities.Transaction>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual System.DateTime TransactionDate { get; set; }
    			public virtual decimal Amount { get; set; }
    			public virtual int Status { get; set; }
    			public virtual int CarParkId { get; set; }
    			public virtual int ParkingLotId { get; set; }
    			public virtual string AspNetUserId { get; set; }
    	
    	public TransactionViewModel() : base() { }
    	public TransactionViewModel(Capstone.Models.Entities.Transaction entity) : base(entity) { }
    
    }
}
